shapiro.test(babydata$wt)
shapiro.test(babydata$ht)
shapiro.test(babydata$mwt)
shapiro.test(babydata$dht)
shapiro.test(babydata$dwt)
shapiro.test(babydata$smoke)
plot(age~parity, data=babydata)
boxplot(wt~smoke, data=babydata)
boxplot(wt~time, data=babydata)
tapply(babydata$wt, babydata$smoke, summary)
tapply(babydata$wt, babydata$time, summary)